### ISSUE TITLE
Error in QM9 example

### ISSUE THREAD

**Issue by delta2323** [pfnet-research/chainer-chemistry#29]
Code to reproduce

```
$ cd examples
$ python tox21/train_tox21.py --method nfp --conv-layers 1 --gpu -1 --epoch 1 --unit-num 10
$ python qm9/train_qm9.py --method nfp --conv_layers 1 --gpu -1 --epoch 1 --unit_num 10
```

Error log (when running train_qm9.py)
```
$ python qm9/train_qm9.py --method nfp --conv_layers 1 --gpu -1 --epoch 1 --unit_num 10
load from cache input/nfp_all
preprocessing dataset...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 133885/133885 [01:08<00:00, 1951.58it/s]
Traceback (most recent call last):
  File "qm9/train_qm9.py", line 208, in <module>
    main()
  File "qm9/train_qm9.py", line 127, in main
    os.makedirs(cache_dir)
  File "/Users/oonokenta/.pyenv/versions/anaconda3-4.3.0/envs/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'input/nfp_all'
```

**Comment by corochann** [comment]
This causes because the `input` dir is created from relative path?
Maybe I was implicitly expecting that the example code is executed in each directory.

```
$ cd examples/tox21
$ python train_tox21.py --method nfp --conv-layers 1 --gpu -1 --epoch 1 --unit-num 10
$ cd ../qm9
$ python qm9/train_qm9.py --method nfp --conv_layers 1 --gpu -1 --epoch 1 --unit_num 10
```

So we should write examples to explicitly make `input` directory under each example folder?

**Comment by delta2323** [comment]
I think restricting the location in which code should run does not solve the problem. In QM9 example, we check existence of the cache directory, not the data file itself. So if we create an empty directory in any location, name it `input/nfp_all`, and execute the code from the location, the same error will occur (even if the location is the example directory). Same is true for the Tox21 example.

```
$ ls
README.md             train_qm9.py          train_qm9_features.py
$ mkdir -p input/nfp_all
$ python train_qm9.py --method nfp --conv_layers 1 --gpu -1 --epoch 1 --unit_num 10
load from cache input/nfp_all
preprocessing dataset...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 133885/133885 [01:05<00:00, 2036.68it/s]Traceback (most recent call last):
  File "train_qm9.py", line 208, in <module>
    main()
  File "train_qm9.py", line 127, in main
    os.makedirs(cache_dir)
  File "/Users/oonokenta/.pyenv/versions/anaconda3-4.3.0/envs/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'input/nfp_all'
```
